# Generated by Django 4.2.7 on 2026-08-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_add_live_base_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architecturenode',
            name='ai_generation_source',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='architecturenode',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='architecturenode',
            name='technology',
            field=models.CharField(max_length=255),
        ),
    ]
